services:
  - type: web
    name: waitlist-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        value: "https://your-frontend-domain.com,http://localhost:3000"
      - key: PORT
        fromService:
          type: web
          name: waitlist-api
          envVarKey: PORT
